export const HOME_HEADER_NAV = [
	{ href: "/", label: "Inicio" },
	{ href: "/buscar", label: "Buscar" },
	{ href: "/ofertas", label: "Ofertas" },
	{ href: "/canasta", label: "Canasta" },
] as const;

export const HOME_HERO = {
	heading: "Compará precios. Armá tu canasta. Comprá mejor.",
	body: "Buscá productos y compará precios registrados por EAN cuando el catálogo esté disponible.",
	searchPlaceholder: "Buscar leche, yerba, arroz, aceite...",
	quickSearches: ["leche", "yerba", "arroz", "aceite"],
	signals: ["Comparación por EAN", "Fecha del registro", "Cobertura por supermercado"],
} as const;

export const SMART_BASKET = {
	title: "Canasta ilustrativa",
	summary: "Ejemplo · 4 productos",
	basketLabel: "Ejemplo de canasta",
	comparisonLabel: "Comparación ilustrativa de canastas",
	totalsLabel: "Totales ilustrativos; no representan una canasta actual.",
	products: [
		{
			name: "Leche entera 1L",
			brand: "La Serenísima Clásica",
			shortLabel: "LE",
			tone: "mint",
		},
		{
			name: "Yerba mate 1kg",
			brand: "Taragüí Tradicional",
			shortLabel: "YM",
			tone: "blue",
		},
		{
			name: "Arroz largo fino 1kg",
			brand: "Gallo Oro",
			shortLabel: "AR",
			tone: "orange",
		},
		{
			name: "Aceite girasol 1,5L",
			brand: "Natura",
			shortLabel: "AC",
			tone: "yellow",
		},
	],
	ranking: [
		{
			supermarket: "Vea",
			mark: "Vea",
			total: "$ 10.847",
			coverage: "4/4 productos",
			status: "Completa",
			badge: "Ejemplo · mejor canasta completa",
			accent: "green",
		},
		{
			supermarket: "Carrefour",
			mark: "C",
			total: "$ 11.236",
			coverage: "4/4 productos",
			status: "Completa",
			accent: "blue",
			badge: null,
		},
		{
			supermarket: "DIA",
			mark: "DIA",
			total: "$ 11.985",
			coverage: "3/4 productos",
			status: "Falta 1",
			accent: "red",
			badge: null,
		},
		{
			supermarket: "Jumbo",
			mark: "Jumbo",
			total: "$ 12.509",
			coverage: "4/4 productos",
			status: "Completa",
			accent: "green",
			badge: null,
		},
	],
	note: "Ejemplo ilustrativo: verificá fecha y fuente antes de comparar precios registrados.",
} as const;

export const HOME_PRODUCT_ROWS = [
	{
		product: "Leche entera 1L",
		brand: "La Serenísima Clásica",
		shortLabel: "LE",
		tone: "mint",
		minPrice: "$ 1.099",
		supermarket: "Vea",
		range: "$ 1.099 - $ 1.349",
		updatedAt: "Ejemplo ilustrativo",
		action: "Buscar producto",
	},
	{
		product: "Yerba mate 1kg",
		brand: "Taragüí Tradicional",
		shortLabel: "YM",
		tone: "blue",
		minPrice: "$ 2.150",
		supermarket: "Carrefour",
		range: "$ 2.150 - $ 2.599",
		updatedAt: "Ejemplo ilustrativo",
		action: "Buscar producto",
	},
	{
		product: "Arroz largo fino 1kg",
		brand: "Gallo Oro",
		shortLabel: "AR",
		tone: "orange",
		minPrice: "$ 1.699",
		supermarket: "Vea",
		range: "$ 1.699 - $ 2.299",
		updatedAt: "Ejemplo ilustrativo",
		action: "Buscar producto",
	},
	{
		product: "Aceite girasol 1,5L",
		brand: "Natura",
		shortLabel: "AC",
		tone: "yellow",
		minPrice: "$ 2.849",
		supermarket: "Vea",
		range: "$ 2.849 - $ 3.599",
		updatedAt: "Ejemplo ilustrativo",
		action: "Buscar producto",
	},
] as const;

export const MARKET_PULSE_ITEMS = [
	{
		title: "Referencia de yerba",
		description: "Lectura ilustrativa de un registro para comparar.",
		value: "Registro",
		tone: "green",
		points: "4,14 16,20 28,12 40,28 52,18 64,34 76,38",
	},
	{
		title: "Rango de aceite",
		description: "Lectura ilustrativa de una diferencia entre supermercados.",
		value: "Rango",
		tone: "amber",
		points: "4,12 16,24 28,18 40,32 52,20 64,28 76,16",
	},
	{
		title: "Cobertura de leche",
		description: "Lectura ilustrativa de una comparación por EAN.",
		value: "Cobertura",
		tone: "green",
		points: "4,28 16,22 28,26 40,18 52,24 64,20 76,24",
	},
] as const;

export function getApprovedHomeCopy() {
	return [
		...HOME_HEADER_NAV.map((item) => item.label),
		HOME_HERO.heading,
		HOME_HERO.body,
		HOME_HERO.searchPlaceholder,
		...HOME_HERO.quickSearches,
		...HOME_HERO.signals,
		SMART_BASKET.title,
		SMART_BASKET.summary,
		SMART_BASKET.basketLabel,
		SMART_BASKET.comparisonLabel,
		SMART_BASKET.totalsLabel,
		SMART_BASKET.note,
		...SMART_BASKET.products.flatMap((item) => [item.name, item.brand]),
		...SMART_BASKET.ranking.flatMap((item) => [
			item.supermarket,
			item.total,
			item.coverage,
			item.status,
			item.badge ?? "",
		]),
		"Ejemplo de precios por producto",
		"4 productos de ejemplo",
		"Estos precios son ejemplos ilustrativos; no son precios actuales.",
		"Abrir búsqueda de productos",
		...HOME_PRODUCT_ROWS.flatMap((item) => [
			item.product,
			item.brand,
			item.minPrice,
			item.supermarket,
			item.range,
			item.updatedAt,
			item.action,
		]),
		"Ejemplos de lectura del catálogo",
		"Las líneas son ilustrativas y no representan una serie observada.",
		"Ver ofertas disponibles",
		...MARKET_PULSE_ITEMS.flatMap((item) => [
			item.title,
			item.description,
			item.value,
		]),
	].filter(Boolean);
}
