import { createHash, randomUUID } from "node:crypto";
import { spawnSync } from "node:child_process";
import { closeSync, fsyncSync, lstatSync, mkdirSync, openSync, readFileSync, renameSync, writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { loadEnvConfig } from "@next/env";
type User = { external_id?: unknown; public_metadata?: unknown; id?: unknown; email_addresses?: unknown };
type Route = { category: "authorized-admin" | "unauthenticated-admin" | "public-catalog"; status: number; claimPresence: boolean }; type RouteAttempt = { category: "authorized-admin"; expectedStatus: number; observedStatus: number | "no_response"; adminClaimPresent: boolean; outcome: "matched" | "status_mismatch" | "no_response" }; type ActorCleanup = "not_created" | "revoked" | "already_consumed" | "cleanup_failed"; type CleanupReceipt = { revokedSessions: "zero" | "one_or_more" | "not_admitted"; actorCleanup: ActorCleanup; browserClose: "closed" | "not_started" | "close_failed"; runtimeExit: "exited" | "not_started" | "exit_unverified"; zeroSessions: "zero" | "one_or_more" | "not_admitted" };
type Command = { command: string; args: string[] }; const confirmation = "NEXT16_S5_DEVELOPMENT_CONFIRMED";
const stages = ["preflight", "target_resolved", "identity_selected", "actor_created", "ticket_consumed", "session_discovered", "session_token_minted", "jwt_act_verified", "admin_claim_verified", "runtime_started", "authorized_route_verified", "public_control_verified", "unauthenticated_control_verified", "evidence_persisted", "session_revoked", "actor_cleanup_classified", "zero_sessions_verified", "complete"] as const;
type Stage = typeof stages[number]; type Failure = "command_failed" | "json_shape_rejected" | "target_mismatch" | "confirmation_missing_or_invalid" | "missing_identifiers" | "wrong_environment" | "ticket_acceptance_failed" | "session_discovery_failed" | "token_mint_failed" | "claim_verification_failed" | "runtime_failed" | "route_failed" | "cleanup_failed"; type Disposition = "verified" | "not_applicable" | "not_admitted"; type StageRecord = { stage: Stage; outcome: "passed" | "failed"; disposition: Disposition; errorCategory: Failure | "none"; evidenceHash: string };
const hash = (value: string | Buffer) => `sha256:${createHash("sha256").update(value).digest("hex")}`;
const manualAdminBindingPaths = ["src/app/admin/layout.tsx", "src/lib/admin/access.ts", "src/proxy.ts", "package.json", "next.config.ts", "scripts/next16-authorized-smoke.ts"] as const;
export function deriveManualAdminCandidateIdentity(root = process.cwd(), paths: readonly string[] = manualAdminBindingPaths) { if (paths.length !== manualAdminBindingPaths.length || paths.some((path, index) => path !== manualAdminBindingPaths[index])) throw new Error("manual_candidate_binding_rejected"); try { const boundary = resolve(root), inputs = paths.map((path) => { const file = resolve(boundary, path); if (relative(boundary, file).startsWith("..") || !lstatSync(file).isFile()) throw new Error("invalid"); return { path, sha256: hash(readFileSync(file)) }; }); return hash(JSON.stringify(inputs)); } catch { throw new Error("manual_candidate_binding_rejected"); } }
export function reconcileManualAdminEvidence(input: { successfulAdminResponses: number; adminErrors: number; priorAnonymousRedirect: boolean; freshAnonymousRedirect: boolean; publicCatalog: string }) { if (input.successfulAdminResponses !== 9 || input.adminErrors !== 0 || !input.priorAnonymousRedirect || !input.freshAnonymousRedirect || input.publicCatalog !== "expected_nonempty") throw new Error("manual_evidence_rejected"); const evidence = { schema: "next16-manual-admin-evidence/v1", candidate: deriveManualAdminCandidateIdentity(), authorized: "server_rendered", anonymous: "redirected_twice", publicCatalog: "expected_nonempty", visualCorrectness: "not_claimed" } as const; return { ...evidence, revision: hash(JSON.stringify(evidence)) }; }
const json = (value: string) => JSON.parse(value) as unknown;
const record = (value: unknown): value is Record<string, unknown> => Boolean(value) && typeof value === "object" && !Array.isArray(value);
export const extractRecords = (value: unknown) => Array.isArray(value) ? value : record(value) && Array.isArray(value.data) ? value.data : [];
const requireRecords = (value: unknown) => Array.isArray(value) ? value : record(value) && Array.isArray(value.data) ? value.data : (() => { throw new Error("json_shape_rejected"); })();
export function requireDevelopmentConfirmation(input: { target?: string; confirmation?: string; matches?: number }) { if (input.confirmation !== confirmation) throw new Error("confirmation_missing_or_invalid"); if (input.target !== "development" || input.matches !== 1) throw new Error("target_mismatch"); return "development"; }
const marked = (user: User, marker: string) => user.external_id === marker || Array.isArray(user.email_addresses) && user.email_addresses.some((email) => record(email) && typeof email.email_address === "string" && email.email_address.includes(marker));
export function selectDedicatedAdmin(users: User[], marker: string) { if (users.filter((user) => marked(user, marker) && record(user.public_metadata) && user.public_metadata.role === "admin").length !== 1) throw new Error("dedicated admin identity rejected"); return { marker }; }
export function validateLiveClaims(claims: unknown) { if (!record(claims) || typeof claims.sid !== "string" || !claims.sid || typeof claims.iss !== "string" || !claims.iss || !record(claims.metadata) || claims.metadata.role !== "admin") throw new Error("live claim rejected"); return { act: record(claims.act), admin: true, session: true }; }
export const categorizeRoute = (path: string, status: number, claimPresence: boolean): Route => path === "/admin" ? { category: claimPresence ? "authorized-admin" : "unauthenticated-admin", status, claimPresence } : { category: "public-catalog", status, claimPresence };
export function selectSessionJwtEndpoint(catalog: string) { const match = catalog.match(/POST\s+(\/sessions\/\{session_id\}\/tokens)(?:\s|$)/im); if (!match) throw new Error("required Clerk command unavailable"); return match[1]; }
export function buildDirectRequest(token: string) { return { redirect: "manual" as const, headers: { accept: "text/html,application/xhtml+xml", "user-agent": "next16-s5-direct-proof", authorization: `Bearer ${token}` } }; }
export function redactRequest(input: Record<string, string>) { return Object.keys(input).filter((key) => !["authorization", "cookie"].includes(key.toLowerCase())).sort(); }
export function classifyDirectRoutes(input: { authorizedStatus: number; publicStatus: number; publicHasProduct: boolean; anonymousStatus: number }) { if (input.authorizedStatus !== 200 || input.publicStatus !== 200 || !input.publicHasProduct || input.anonymousStatus < 300 || input.anonymousStatus > 399) throw new Error("route_failed"); return { authorized: "status_200", public: "status_200_nonempty", anonymous: "denied_3xx" } as const; }
export const buildEvidenceManifest = (input: { snapshot: string; routes: Route[] }) => hash(JSON.stringify({ snapshot: hash(input.snapshot), routes: input.routes }));
export function recordRouteAttempt(attempts: unknown[], input: { category: "authorized-admin"; expectedStatus: number; observedStatus?: number; adminClaimPresent: boolean }) { const observedStatus = Number.isInteger(input.observedStatus) && input.observedStatus! >= 100 && input.observedStatus! <= 599 ? input.observedStatus! : "no_response", outcome = observedStatus === input.expectedStatus ? "matched" : observedStatus === "no_response" ? "no_response" : "status_mismatch", attempt: RouteAttempt = { ...input, observedStatus, outcome }; attempts.push(attempt); if (outcome !== "matched") throw new Error("route_failed"); return attempt; }
export function buildCleanupReceipt(input: { revokedSessions?: number; actorCleanup: ActorCleanup; browserClose: CleanupReceipt["browserClose"]; runtimeExit: CleanupReceipt["runtimeExit"]; zeroSessions?: number }): CleanupReceipt { const category = (count: number | undefined) => { if (count === undefined) return "not_admitted" as const; if (!Number.isSafeInteger(count) || count < 0) throw new Error("cleanup receipt rejected"); return count ? "one_or_more" as const : "zero" as const; }; return { revokedSessions: category(input.revokedSessions), actorCleanup: input.actorCleanup, browserClose: input.browserClose, runtimeExit: input.runtimeExit, zeroSessions: category(input.zeroSessions) }; }
export function createOneTokenGuard<T>(create: () => T) { let attempted = false; return () => { if (attempted) throw new Error("actor creation already attempted"); attempted = true; return create(); }; }
export function createStageJournal() { let index = -1; const records: StageRecord[] = [], classify = (stage: Stage, error: unknown): Failure => { const message = error instanceof Error ? error.message : ""; if (["command_failed", "json_shape_rejected", "target_mismatch", "confirmation_missing_or_invalid", "missing_identifiers", "wrong_environment"].includes(message)) return message as Failure; if (message === "authorized Clerk command rejected" || message === "required Clerk command unavailable" || message === "trusted Clerk doctor rejected") return "command_failed"; return (({ target_resolved: "target_mismatch", actor_created: "missing_identifiers", ticket_consumed: "ticket_acceptance_failed", session_discovered: "session_discovery_failed", session_token_minted: "token_mint_failed", jwt_act_verified: "claim_verification_failed", admin_claim_verified: "claim_verification_failed", runtime_started: "runtime_failed", authorized_route_verified: "route_failed", public_control_verified: "route_failed", unauthenticated_control_verified: "route_failed" } as Partial<Record<Stage, Failure>>)[stage] ?? "cleanup_failed"); }, write = (stage: Stage, outcome: StageRecord["outcome"], errorCategory: StageRecord["errorCategory"], disposition: Disposition = "verified") => { const next = stages.indexOf(stage); if (next <= index || (next > index + 1 && next < stages.indexOf("session_revoked"))) throw new Error("stage order rejected"); index = next; const result = { stage, outcome, disposition, errorCategory, evidenceHash: hash(`${stage}:${outcome}:${disposition}:${errorCategory}`) }; records.push(result); return result; }; return { pass: (stage: Stage) => write(stage, "passed", "none"), fail: (stage: Stage, error: unknown) => write(stage, "failed", classify(stage, error)), skip: (stage: Stage, disposition: Exclude<Disposition, "verified">) => write(stage, "passed", "none", disposition), records: () => records.slice(), summary: () => ({ rootFailureStage: records.find((entry) => entry.outcome === "failed")?.stage, finalCleanupStage: records.filter((entry) => stages.indexOf(entry.stage) >= stages.indexOf("session_revoked")).at(-1)?.stage, finalStage: records.at(-1)?.stage }) }; }
export async function withCleanup<T>(proof: () => Promise<T>, cleanup: () => Promise<void>) { let result: T | undefined; let failure: unknown; try { result = await proof(); } catch (error) { failure = error; } try { await cleanup(); } catch (error) { throw error; } if (failure) throw failure; return result as T; }
const clerk = (): Command => process.env.NEXT16_S5_CLERK_CLI ? { command: process.env.NEXT16_S5_CLERK_CLI, args: [] } : { command: "npx", args: ["-y", "clerk@latest"] };
function run(command: Command, args: string[]) { const result = spawnSync(command.command, [...command.args, ...args], { encoding: "utf8", stdio: "pipe" }); if (result.error || result.status) throw new Error("authorized Clerk command rejected"); return result.stdout; }
function help(command: Command, args: string[], flags: string[]) { const output = run(command, [...args, "--help"]); if (!flags.every((flag) => output.includes(flag))) throw new Error("required Clerk command unavailable"); }
function doctor(command: Command) { const result = spawnSync(command.command, [...command.args, "doctor", "--json"], { encoding: "utf8", stdio: "pipe" }), parsed = json(result.stdout), checks = Array.isArray(parsed) ? parsed : record(parsed) && Array.isArray(parsed.checks) ? parsed.checks : []; if (! ["Host execution", "Logged in", "Authentication valid"].every((name) => checks.some((check) => record(check) && check.name === name && check.status === "pass"))) throw new Error("trusted Clerk doctor rejected"); }
export function normalizeDevelopmentTarget(apps: unknown, publicKey: string, input: { target?: string; confirmation?: string }) { const matches = requireRecords(apps).flatMap((app) => record(app) && Array.isArray(app.instances) ? app.instances.filter((instance) => record(instance) && (instance.publishable_key === publicKey || instance.publishableKey === publicKey)).map((instance) => ({ app, instance })) : []); requireDevelopmentConfirmation({ ...input, matches: matches.length }); const match = matches[0], app = record(match.app) ? match.app.application_id ?? match.app.id : undefined, instance = record(match.instance) ? match.instance.instance_id ?? match.instance.id : undefined, environment = record(match.instance) ? match.instance.environment_type ?? match.instance.environment : undefined; if (typeof app !== "string" || typeof instance !== "string") throw new Error("missing_identifiers"); if (environment !== "development") throw new Error("wrong_environment"); return { app, instance }; }
const api = (command: Command, target: { app: string; instance: string }, path: string) => json(run(command, ["api", path, "--app", target.app, "--instance", target.instance])); const mutate = (command: Command, target: { app: string; instance: string }, path: string) => run(command, ["api", path, "-X", "POST", "--app", target.app, "--instance", target.instance]);
type ReceiptPointer = { manifest: string; revision: string };
const opaqueHash = (value: string) => { if (!/^sha256:[a-f0-9]{64}$/.test(value)) throw new Error("receipt hash rejected"); return value; };
function writeDurably(directory: string, fileName: string, value: unknown) { const source = `${JSON.stringify(value)}\n`, temporary = join(directory, `.${fileName}.${randomUUID()}.tmp`), output = join(directory, fileName); mkdirSync(directory, { recursive: true, mode: 0o700 }); const file = openSync(temporary, "wx", 0o600); try { writeFileSync(file, source); fsyncSync(file); } finally { closeSync(file); } renameSync(temporary, output); const parent = openSync(directory, "r"); try { fsyncSync(parent); } finally { closeSync(parent); } return source; }
function writeReceipt(fileName: "attempted-route.json" | "cleanup.json" | "evidence.json", value: unknown, root = join(process.cwd(), "audit", "next16-authorized-smoke")): ReceiptPointer { const source = `${JSON.stringify(value)}\n`, manifest = hash(source), directory = join(root, manifest, randomUUID()); writeDurably(directory, fileName, value); return { manifest, revision: hash(`${manifest}\n`) }; }
function writeEvidence(value: unknown): ReceiptPointer { return writeReceipt("evidence.json", value); }
export function persistAttemptedRoute(input: { category: "authorized-admin"; expectedStatus: number; observedStatus?: number; adminClaimPresent: boolean; snapshotHash: string; releaseHash: string }, root?: string, onPersisted?: (receipt: ReceiptPointer, attempt: RouteAttempt) => void) { const attempts: unknown[] = [], attempt = recordRouteAttempt.bind(null, attempts); try { attempt(input); } catch (error) { const recorded = attempts[0] as RouteAttempt, receipt = { category: recorded.category, expectedStatus: recorded.expectedStatus, observedStatus: recorded.observedStatus, adminClaimPresent: recorded.adminClaimPresent, resultCategory: recorded.outcome, snapshotHash: opaqueHash(input.snapshotHash), releaseHash: opaqueHash(input.releaseHash) }, pointer = writeReceipt("attempted-route.json", receipt, root); onPersisted?.(pointer, recorded); throw error; } const recorded = attempts[0] as RouteAttempt, receipt = { category: recorded.category, expectedStatus: recorded.expectedStatus, observedStatus: recorded.observedStatus, adminClaimPresent: recorded.adminClaimPresent, resultCategory: recorded.outcome, snapshotHash: opaqueHash(input.snapshotHash), releaseHash: opaqueHash(input.releaseHash) }, pointer = writeReceipt("attempted-route.json", receipt, root); onPersisted?.(pointer, recorded); return recorded; }
export function persistCleanupReceipt(receipt: CleanupReceipt, root?: string) { return writeReceipt("cleanup.json", receipt, root); }
async function smoke() {
  loadEnvConfig(process.cwd()); const command = clerk(), sessionId = process.env.NEXT16_S5_SESSION_ID ?? "", states = { authorized: "not_observed", public: "not_observed", anonymous: "not_observed" }; let target: { app: string; instance: string } | undefined, user: User | undefined, claims = { act: false, admin: false, session: false }, token = "", snapshotHash = "", releaseHash = "", evidence: ReceiptPointer | undefined, cleanupFailed = false, revoked = "not_attempted", zeroSessions = "not_admitted", failed = false, sessionVerified = false;
  const persist = () => evidence = writeEvidence({ schema: "next16-direct-authorized-smoke/v5", routes: states, adminClaimPresent: claims.admin, sessionHash: sessionId ? hash(sessionId) : "not_admitted", snapshotHash, releaseHash, requestHeaders: redactRequest(token ? buildDirectRequest(token).headers : {}) }); const active = () => target && user && typeof user.id === "string" ? extractRecords(api(command, target, `/sessions?user_id=${encodeURIComponent(user.id)}&limit=100`)).filter((session) => record(session) && session.status === "active") : [];
  try {
    doctor(command); help(command, ["api"], ["-X"]); target = normalizeDevelopmentTarget(json(run(command, ["apps", "list", "--json"])), process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY ?? "", { target: process.env.NEXT16_S5_TARGET, confirmation: process.env.NEXT16_S5_CONFIRMATION }); if (!sessionId) throw new Error("missing_identifiers"); const session = api(command, target, `/sessions/${encodeURIComponent(sessionId)}`), users = extractRecords(api(command, target, "/users?limit=100")) as User[]; user = record(session) && typeof session.user_id === "string" ? users.find((value) => value.id === session.user_id && record(value.public_metadata) && value.public_metadata.role === "admin") : undefined; if (!user || typeof user.id !== "string" || !record(session) || session.user_id !== user.id || session.status !== "active") throw new Error("current session rejected"); sessionVerified = true; releaseHash = hash(readFileSync(join(process.cwd(), ".next", "BUILD_ID"))); snapshotHash = hash(`${releaseHash}:${hash(readFileSync(join(process.cwd(), "package.json")))}`); const endpoint = selectSessionJwtEndpoint(run(command, ["api", "ls", "token"])); const minted = json(run(command, ["api", endpoint.replace("{session_id}", encodeURIComponent(sessionId)), "-X", "POST", "--app", target.app, "--instance", target.instance])); token = record(minted) && typeof minted.jwt === "string" ? minted.jwt : ""; if (!token) throw new Error("token_mint_failed"); const { verifyToken } = await import("@clerk/nextjs/server"), signed = await verifyToken(token, { secretKey: process.env.CLERK_SECRET_KEY, jwtKey: process.env.CLERK_JWT_KEY }); claims = validateLiveClaims(signed); if (!record(signed) || signed.sid !== sessionId) throw new Error("current session rejected"); const authorized = await fetch("http://127.0.0.1:3000/admin", buildDirectRequest(token)); states.authorized = `status_${authorized.status}`; persist(); const publicResponse = await fetch("http://127.0.0.1:3000/api/products?limit=1", { headers: { accept: "application/json" }, redirect: "manual" }); states.public = `status_${publicResponse.status}`; persist(); const publicBody = await publicResponse.json() as unknown; states.public = publicResponse.status === 200 && record(publicBody) && Array.isArray(publicBody.items) && publicBody.items.length ? "status_200_nonempty" : `status_${publicResponse.status}`; persist(); const anonymous = await fetch("http://127.0.0.1:3000/admin", { headers: { accept: "text/html,application/xhtml+xml", "user-agent": "next16-s5-direct-proof" }, redirect: "manual" }); states.anonymous = anonymous.status >= 300 && anonymous.status < 400 ? "denied_3xx" : `status_${anonymous.status}`; persist(); classifyDirectRoutes({ authorizedStatus: authorized.status, publicStatus: publicResponse.status, publicHasProduct: states.public === "status_200_nonempty", anonymousStatus: anonymous.status });
  } catch { failed = true; } finally {
    try { if (target && user && sessionId && sessionVerified) { mutate(command, target, `/sessions/${encodeURIComponent(sessionId)}/revoke`); revoked = "exact_session_revoked"; zeroSessions = active().length === 0 ? "zero" : "one_or_more"; if (zeroSessions !== "zero") throw new Error("cleanup_failed"); } else cleanupFailed = true; } catch { cleanupFailed = true; } finally { persist(); }
  }
  return { outcome: failed || cleanupFailed ? "failed" : "passed", claims, routes: states, cleanup: { revoked, zeroSessions }, evidence: evidence?.manifest ?? "not_admitted", revision: evidence?.revision ?? "not_admitted" };
}
if (process.argv[1]?.endsWith("next16-authorized-smoke.ts")) smoke().then((result) => { console.log(JSON.stringify(result)); if (result.outcome === "failed") process.exitCode = 1; }).catch(() => { console.log(JSON.stringify({ outcome: "failed", failureCategory: "unexpected" })); process.exitCode = 1; });
