GRANT CONNECT ON DATABASE ofertasuper TO ofertasuper_app;
REVOKE CREATE ON SCHEMA public FROM ofertasuper_app;
GRANT USAGE ON SCHEMA public TO ofertasuper_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ofertasuper_app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA public TO ofertasuper_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ofertasuper_owner IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ofertasuper_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ofertasuper_owner IN SCHEMA public GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ofertasuper_app;
