-- Roles are created by the local compose initializer; this file is safe to reapply after ACL-free restore.
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'ofertasuper_runtime') THEN CREATE ROLE ofertasuper_runtime NOLOGIN; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'ofertasuper_authority') THEN CREATE ROLE ofertasuper_authority NOLOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'ofertasuper_verifier') THEN CREATE ROLE ofertasuper_verifier LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS; END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'ofertasuper_verifier_definer') THEN CREATE ROLE ofertasuper_verifier_definer NOLOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS; END IF; END $$;
REVOKE ALL ON DATABASE ofertasuper FROM PUBLIC;
GRANT CONNECT ON DATABASE ofertasuper TO ofertasuper_app, ofertasuper_runtime, ofertasuper_authority;
REVOKE ofertasuper_owner FROM ofertasuper_app, ofertasuper_runtime, ofertasuper_authority;
REVOKE ofertasuper_authority FROM ofertasuper_app, ofertasuper_runtime;
ALTER ROLE ofertasuper_app NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
ALTER ROLE ofertasuper_runtime NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
REVOKE CREATE ON SCHEMA public FROM PUBLIC, ofertasuper_app, ofertasuper_runtime;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM PUBLIC, ofertasuper_app, ofertasuper_runtime;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC, ofertasuper_app, ofertasuper_runtime;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA public FROM PUBLIC, ofertasuper_app, ofertasuper_runtime;
GRANT USAGE ON SCHEMA public TO ofertasuper_app, ofertasuper_runtime;
ALTER TABLE public.products OWNER TO ofertasuper_owner;
ALTER TABLE public.supermarkets OWNER TO ofertasuper_owner;
ALTER TABLE public.supermarket_products OWNER TO ofertasuper_owner;
ALTER TABLE public.price_history OWNER TO ofertasuper_owner;
ALTER TABLE public.promotions OWNER TO ofertasuper_owner;
ALTER TABLE public.promotion_products OWNER TO ofertasuper_owner;
ALTER TABLE public.categories OWNER TO ofertasuper_owner;
ALTER TABLE public.ingestion_run OWNER TO ofertasuper_owner;
ALTER TABLE public.staging_product OWNER TO ofertasuper_owner;
ALTER TABLE public.source_health OWNER TO ofertasuper_owner;
ALTER TABLE public.direct_refresh_run_ledger OWNER TO ofertasuper_owner;
ALTER TABLE public.governed_catalogs OWNER TO ofertasuper_owner;
ALTER TABLE public.catalog_operations OWNER TO ofertasuper_owner;
ALTER TABLE public.serving_products OWNER TO ofertasuper_owner;
ALTER TABLE public.serving_supermarkets OWNER TO ofertasuper_owner;
ALTER TABLE public.serving_offers OWNER TO ofertasuper_owner;
ALTER TABLE public.serving_history OWNER TO ofertasuper_owner;
ALTER TABLE public.serving_promotions OWNER TO ofertasuper_owner;
ALTER TABLE public.serving_memberships OWNER TO ofertasuper_owner;
ALTER TABLE public.production_readiness_promotions OWNER TO ofertasuper_owner;
ALTER TABLE public.production_readiness_receipts OWNER TO ofertasuper_owner;
ALTER TABLE public.production_readiness_publications OWNER TO ofertasuper_owner;
ALTER TABLE public.verifier_envelope_commitments OWNER TO ofertasuper_verifier_definer;
ALTER TABLE public.promotion_ready_envelope_admissions OWNER TO ofertasuper_verifier_definer;
ALTER TABLE public.promotion_ready_envelope_items OWNER TO ofertasuper_verifier_definer;
ALTER SEQUENCE public.supermarkets_id_seq OWNER TO ofertasuper_owner;
ALTER SEQUENCE public.supermarket_products_id_seq OWNER TO ofertasuper_owner;
ALTER SEQUENCE public.price_history_id_seq OWNER TO ofertasuper_owner;
ALTER SEQUENCE public.promotions_id_seq OWNER TO ofertasuper_owner;
ALTER SEQUENCE public.categories_id_seq OWNER TO ofertasuper_owner;
ALTER SEQUENCE public.ingestion_run_id_seq OWNER TO ofertasuper_owner;
ALTER SEQUENCE public.staging_product_id_seq OWNER TO ofertasuper_owner;
ALTER SEQUENCE public.source_health_id_seq OWNER TO ofertasuper_owner;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.products, public.supermarkets, public.supermarket_products, public.price_history, public.promotions, public.promotion_products, public.categories, public.ingestion_run, public.staging_product, public.source_health, public.direct_refresh_run_ledger TO ofertasuper_app;
GRANT USAGE, SELECT ON SEQUENCE public.supermarkets_id_seq, public.supermarket_products_id_seq, public.price_history_id_seq, public.promotions_id_seq, public.categories_id_seq, public.ingestion_run_id_seq, public.staging_product_id_seq, public.source_health_id_seq TO ofertasuper_app;
ALTER FUNCTION public.guard_governed_catalog_mutation() OWNER TO ofertasuper_owner;
REVOKE EXECUTE ON FUNCTION public.governed_catalog_begin_baseline(text, text, text, bigint) FROM ofertasuper_app;
GRANT EXECUTE ON FUNCTION public.governed_catalog_begin_baseline(text, text, text, text, bigint, bigint, timestamptz) TO ofertasuper_app;
REVOKE EXECUTE ON FUNCTION public.capture_source_delta(text, text, jsonb) FROM PUBLIC, ofertasuper_runtime, ofertasuper_verifier;
ALTER FUNCTION public.capture_source_delta(text, text, jsonb) OWNER TO ofertasuper_owner;
ALTER FUNCTION public.capture_source_delta(text, text, jsonb) SECURITY DEFINER;
ALTER FUNCTION public.capture_source_delta(text, text, jsonb) SET search_path = pg_catalog, pg_temp;
GRANT EXECUTE ON FUNCTION public.capture_source_delta(text, text, jsonb) TO ofertasuper_app;
REVOKE EXECUTE ON FUNCTION public.activate_authority(jsonb), public.inspect_authority(text, text, text), public.revoke_authority(jsonb) FROM PUBLIC, ofertasuper_app, ofertasuper_runtime, ofertasuper_verifier;
GRANT EXECUTE ON FUNCTION public.activate_authority(jsonb), public.inspect_authority(text, text, text), public.revoke_authority(jsonb) TO ofertasuper_authority;
REVOKE EXECUTE ON FUNCTION public.promote_delta(jsonb) FROM PUBLIC, ofertasuper_app, ofertasuper_runtime, ofertasuper_verifier;
GRANT EXECUTE ON FUNCTION public.promote_delta(jsonb) TO ofertasuper_authority;
GRANT SELECT ON TABLE public.authority_candidates, public.candidate_technical_verifications, public.refresh_policies, public.publication_grants, public.approval_challenges, public.approval_receipts TO ofertasuper_app;
REVOKE EXECUTE ON FUNCTION public.create_approval_challenge(text,text,text,text,text,text,text,timestamptz,timestamptz), public.consume_approval_challenge(text), public.record_candidate_approval_receipt(text,text,text,timestamptz,text), public.prepare_authority_revoke_consent(jsonb), public.record_authority_revoke_consent(jsonb) FROM PUBLIC, ofertasuper_app, ofertasuper_runtime, ofertasuper_verifier;
GRANT EXECUTE ON FUNCTION public.create_approval_challenge(text,text,text,text,text,text,text,timestamptz,timestamptz), public.consume_approval_challenge(text), public.record_candidate_approval_receipt(text,text,text,timestamptz,text), public.prepare_authority_revoke_consent(jsonb), public.record_authority_revoke_consent(jsonb) TO ofertasuper_authority;
GRANT SELECT ON TABLE public.governed_catalogs, public.serving_products, public.serving_supermarkets, public.serving_offers, public.serving_history, public.serving_promotions, public.serving_memberships TO ofertasuper_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE ofertasuper_owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES FOR ROLE ofertasuper_owner IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC, ofertasuper_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ofertasuper_owner IN SCHEMA public REVOKE ALL ON SEQUENCES FROM PUBLIC, ofertasuper_app;
ALTER DEFAULT PRIVILEGES FOR ROLE ofertasuper_owner IN SCHEMA public REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC, ofertasuper_app;
ALTER ROLE "ofertasuper_verifier" LOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
ALTER ROLE "ofertasuper_verifier_definer" NOLOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT CONNECT ON DATABASE "ofertasuper" TO "ofertasuper_verifier";
REVOKE "ofertasuper_owner" FROM "ofertasuper_verifier";
REVOKE "ofertasuper_verifier" FROM "ofertasuper_app", "ofertasuper_runtime";
REVOKE "ofertasuper_app", "ofertasuper_runtime" FROM "ofertasuper_verifier";
REVOKE CREATE ON SCHEMA "public" FROM "ofertasuper_verifier";
REVOKE ALL ON ALL TABLES IN SCHEMA "public" FROM "ofertasuper_verifier";
REVOKE ALL ON ALL SEQUENCES IN SCHEMA "public" FROM "ofertasuper_verifier";
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA "public" FROM "ofertasuper_verifier";
GRANT USAGE ON SCHEMA "public" TO "ofertasuper_verifier";
GRANT SELECT ON TABLE "public"."products", "public"."supermarkets", "public"."supermarket_products", "public"."price_history", "public"."promotions", "public"."promotion_products", "public"."categories", "public"."ingestion_run", "public"."staging_product", "public"."source_health", "public"."direct_refresh_run_ledger", "public"."governed_catalogs", "public"."catalog_operations", "public"."serving_products", "public"."serving_supermarkets", "public"."serving_offers", "public"."serving_history", "public"."serving_promotions", "public"."serving_memberships", "public"."production_readiness_promotions", "public"."production_readiness_receipts", "public"."production_readiness_publications", "public"."source_capture_operations", "public"."source_capture_items", "public"."delta_verifications", "public"."evidence_artifacts", "public"."evidence_references", "public"."evidence_dependencies", "public"."evidence_restrictions" TO "ofertasuper_verifier";
-- "public"."commit_promotion_ready_envelope"(bytea, text) and future "public"."admit_promotion_ready_envelopes"(jsonb) use session_user as caller provenance; current_user is the definer and not caller provenance.
DO $verifier_acl$ DECLARE target regprocedure; BEGIN FOREACH target IN ARRAY ARRAY[pg_catalog.to_regprocedure('public.commit_promotion_ready_envelope(bytea,text)'), pg_catalog.to_regprocedure('public.admit_promotion_ready_envelopes(jsonb)')] LOOP IF target IS NOT NULL THEN IF NOT (SELECT p.prosecdef AND p.proconfig = ARRAY['search_path=pg_catalog, pg_temp'] FROM pg_catalog.pg_proc p WHERE p.oid = target) THEN RAISE EXCEPTION 'unsafe verifier boundary'; END IF; EXECUTE pg_catalog.format('ALTER FUNCTION %s OWNER TO "ofertasuper_verifier_definer"', target); EXECUTE pg_catalog.format('REVOKE EXECUTE ON FUNCTION %s FROM PUBLIC, "ofertasuper_app", "ofertasuper_runtime"', target); EXECUTE pg_catalog.format('GRANT EXECUTE ON FUNCTION %s TO "ofertasuper_verifier"', target); END IF; END LOOP; IF pg_catalog.to_regprocedure('public.canonical_json_text(jsonb)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION "public"."canonical_json_text"(jsonb) OWNER TO "ofertasuper_verifier_definer"'; EXECUTE 'REVOKE EXECUTE ON FUNCTION "public"."canonical_json_text"(jsonb) FROM PUBLIC, "ofertasuper_app", "ofertasuper_runtime", "ofertasuper_verifier"'; END IF; IF pg_catalog.to_regprocedure('public.envelope_items_ordered(jsonb)') IS NOT NULL THEN EXECUTE 'ALTER FUNCTION "public"."envelope_items_ordered"(jsonb) OWNER TO "ofertasuper_verifier_definer"'; EXECUTE 'REVOKE EXECUTE ON FUNCTION "public"."envelope_items_ordered"(jsonb) FROM PUBLIC, "ofertasuper_app", "ofertasuper_runtime", "ofertasuper_verifier"'; END IF; END $verifier_acl$;
